package pages;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class CreateNewUserPage {

    WebDriver driver = null;
    By emailTextFieldSearch = By.xpath("/html[1]/body[1]/teamo-root[1]/div[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[2]/teamo-create-user[1]/div[1]/mat-card[1]/mat-card-content[1]/form[1]/p[2]/mat-form-field[1]/div[1]/div[1]/div[1]/input[1]");
    By nameTextFieldSearch = By.xpath("/html[1]/body[1]/teamo-root[1]/div[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[2]/teamo-create-user[1]/div[1]/mat-card[1]/mat-card-content[1]/form[1]/p[3]/mat-form-field[1]/div[1]/div[1]/div[1]/input[1]");
    By lastNameTextFieldSearch = By.xpath("/html[1]/body[1]/teamo-root[1]/div[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[2]/teamo-create-user[1]/div[1]/mat-card[1]/mat-card-content[1]/form[1]/p[4]/mat-form-field[1]/div[1]/div[1]/div[1]/input[1]");
    By pwTextFieldSearch = By.id("autogeneratedPassword");
    By rolesSectionSearch = By.xpath("/html[1]/body[1]/teamo-root[1]/div[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[2]/teamo-create-user[1]/div[1]/mat-card[1]/mat-card-content[1]/form[1]/mat-expansion-panel[1]/mat-expansion-panel-header[1]");
    By rolesDropDownFieldSearch = By.xpath("/html[1]/body[1]/teamo-root[1]/div[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[2]/teamo-create-user[1]/div[1]/mat-card[1]/mat-card-content[1]/form[1]/mat-expansion-panel[1]/div[1]/div[1]/form[1]/p[1]/mat-form-field[1]/div[1]/div[1]/div[1]");
    By firstRole = By.xpath("/html[1]/body[1]/div[2]/div[2]/div[1]/div[1]/mat-option[1]/span[1]");
    By firstOrgSearch = By.xpath("//span[contains(text(),'Pragmatio solutions')]");
    By orgDropDownFieldSearch = By.xpath("/html[1]/body[1]/teamo-root[1]/div[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[2]/teamo-create-user[1]/div[1]/mat-card[1]/mat-card-content[1]/form[1]/mat-expansion-panel[1]/div[1]/div[1]/form[1]/p[2]/mat-form-field[1]/div[1]/div[1]");
    By addRoleBtnSearch = By.xpath("//mat-icon[text()='control_point']");
    By createBtnSearch = By.xpath("//text()[.='Create']/ancestor::button[1]");

    public CreateNewUserPage(WebDriver driver){
        this.driver = driver;
    }

    public boolean formIsDisplayed(){
        return driver.findElement(emailTextFieldSearch).isDisplayed();
    }

    public void enterEmail(String input){
        driver.findElement(emailTextFieldSearch).sendKeys(input);
    }

    public void enterName(String input){
        driver.findElement(nameTextFieldSearch).sendKeys(input);
    }

    public void enterLastName(String input){
        driver.findElement(lastNameTextFieldSearch).sendKeys(input);
    }

    public void enterPassword(String input){
        driver.findElement(pwTextFieldSearch).clear();
        driver.findElement(pwTextFieldSearch).sendKeys(input);
    }

    public void expandRolesSection(){
        WebElement rolesSection = driver.findElement(rolesSectionSearch);
        JavascriptExecutor jse = (JavascriptExecutor) driver;
        jse.executeScript("arguments[0].scrollIntoView(true);", rolesSection);
        //driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        rolesSection.click();
    }

    public void openRoleSelect(){
        driver.findElement(rolesDropDownFieldSearch).click();
    }

    public void selectRole(){
        driver.findElement(firstRole).click();
    }

    public void openOrgSelect(){
        driver.findElement(orgDropDownFieldSearch).click();
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    }

    public void selectOrganisation(){
        WebElement firstOrg;
        WebDriverWait wait = new WebDriverWait(driver, 5);
        firstOrg = wait.until(ExpectedConditions.elementToBeClickable(firstOrgSearch));
        firstOrg.click();
    }

    public void clickAddRoleBtn(){
        driver.findElement(addRoleBtnSearch).click();
    }

    public void clickCreateBtn(){
        WebElement createBtn = driver.findElement(createBtnSearch);
        JavascriptExecutor jse = (JavascriptExecutor)driver;
        jse.executeScript("arguments[0].scrollIntoView(true);",createBtn);
        createBtn.click();
    }
}
